# Generated by Django 5.1.4 on 2024-12-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_feedback_accessibility_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
