# Generated by Django 5.1.4 on 2024-12-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_feedback_phone_number_feedback_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
